polygon_types_to_industry = {
    'airports': 'transport',
    'automotive': 'automotive',
    'chemical': 'manufacturing',
    'construction': 'manufacturing',
    'defence_aerospace': 'manufacturing',
    'distribution_center': 'transport',
    'distribution': 'transport',
    'electronics': 'manufacturing',
    'field': 'mining',
    'food': 'manufacturing',
    'heavy_industry': 'manufacturing',
    'heavy': 'manufacturing',
    'metal': 'manufacturing',
    'mine': 'mining',
    'ports': 'transport',
    'power_plant': 'energy',
    'processing': 'mining',
    'textile': 'manufacturing',
    'waste': 'utilities',
    'water': 'utilities',
    'wood': 'manufacturing',
}
